blank_issues_enabled: false
contact_links:
  - name: â“ Question
    url: https://discord.gg/DFcCNDg7bB
    about: Do you have a question instead of an issue? Meet us in the Discord!
  - name: ğŸ“– Espanso Documentation
    url: https://espanso.org/docs/
    about: Our Espanso documentation shows you how to configure matches, use packages and much more.
  - name: ğŸ§µ Reddit
    url: https://www.reddit.com/r/espanso/
    about: Our official Reddit community in which you can ask questions and receive updates on Espanso.
